### PR TITLE
Bump github upload artifact

### PR DESCRIPTION
**Pull request by luca-della-vedova**
### Fixed bug

The v2 version of `upload-artifacts` is deprecated and is causing failures in downstream repos with the following message:

```
This request has been automatically failed because it uses a deprecated version of `actions/upload-artifact: v2`. Learn more: https://github.blog/changelog/2024-02-13-deprecation-notice-v1-and-v2-of-the-artifact-actions/
```

### Fix applied

Bump it

### CODE REVIEW

**Comment by luca-della-vedova** [comment]
Bundling bumping of other dependencies as well to fix the current deprecation warning:

```
The following actions use a deprecated Node.js version and will be forced to run on node20: actions/cache@v3, actions/upload-artifact@v2, codecov/codecov-action@v1. For more info: https://github.blog/changelog/2024-03-07-github-actions-all-actions-will-run-on-node20-instead-of-node16-by-default/
```

**Comment by Yadunund** [comment]
Any idea why iron jammy is failing?

**Review by arjo129 — APPROVED** [review]
LGTM. Waiting for it to run to completion.

**Review by arjo129 — CHANGES_REQUESTED** [review]
Ignore my previous review. Seems only one case is correctly uploading.

**Review by koonpeng — APPROVED** [review]

**Comment by luca-della-vedova** [comment]
We are now back in only rolling failing

**Review by Yadunund — APPROVED** [review]

**Comment by luca-della-vedova** [comment]
The added `apt upgrade` also made `rolling` on rmf_simulation green (there was an outdated gz-math before) https://github.com/open-rmf/rmf_simulation/pull/131, merging

**Pull request merged**
